services:
  dnsmasq:
    image: alpine:3.18
    container_name: dev-dns
    network_mode: "host"
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges
    privileged: true
    restart: unless-stopped
    entrypoint: [
      "sh",
      "-c",
      "apk add --no-cache dnsmasq && exec dnsmasq -k --log-facility=- --conf-file=/etc/dnsmasq.conf --no-daemon"
    ]

  dnsmasq-gen:
    image: jwilder/docker-gen:0.9.0
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./templates/dnsmasq.tmpl:/etc/docker-gen/templates/dnsmasq.tmpl:ro
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
    entrypoint: /usr/local/bin/docker-gen -notify-sighup dnsmasq -watch -only-exposed /etc/docker-gen/templates/dnsmasq.tmpl /etc/dnsmasq.conf
    restart: unless-stopped
