services:
  dnsmasq:
    image: alpine:3.18
    container_name: dev-dns
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
    restart: unless-stopped
    entrypoint: [
      "sh",
      "-c",
      "apk add --no-cache dnsmasq && exec dnsmasq -k --log-facility=- --conf-file=/etc/dnsmasq.conf"
    ]

  dnsmasq-gen:
    image: jwilder/docker-gen:0.9.0
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./templates/dnsmasq.tmpl:/etc/docker-gen/templates/dnsmasq.tmpl:ro
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
    command: -notify "docker kill -s HUP dev-dns" -watch -only-exposed /etc/docker-gen/templates/dnsmasq.tmpl /etc/dnsmasq.conf
    restart: unless-stopped
